Fix various problems with importing modules
eXist-db/exist pull request #3585
Opened 2020-10-26 14:30 UTC by adamretter

This back-ports some fixes to eXist-db from FusionDB around the handling of `import module`.

**NOTE**: The PR https://github.com/eXist-db/exist/pull/3579 needs to be merged **BEFORE** this one!

1.  Closes https://github.com/eXist-db/exist/issues/1174
2. Now raises correct errors for all cases of:
    1. XQST0047
    2. XQST0034
    3. XQST0049

2020-10-26 15:17 UTC, dizzzz commented on exist-core/src/main/java/org/exist/source/AbstractSource.java
> +import net.jpountz.xxhash.XXHash64;
is this a duplicate from another PR?

2020-10-26 15:20 UTC, dizzzz commented on exist-core/src/main/java/org/exist/xquery/FunctionFactory.java
> +                final boolean throwOnNotFound = i == modules.length - 1;
for me :-) unreadable line

2020-10-26 15:25 UTC, dizzzz commented on exist-core/src/main/java/org/exist/xquery/functions/util/ModuleInfo.java
> +			new FunctionReturnSequenceType(Type.STRING, Cardinality.ONE_OR_MORE, "the description of the active function module identified by the namespace URI"),
need to check: update of monex needed/possible?

2020-10-26 15:28 UTC, dizzzz approved these changes
LGTM ; I hope the 2 PRs add-up...

2020-10-26 15:29 UTC, dizzzz commented
small issue found
![image](https://user-images.githubusercontent.com/1700062/97192623-5e5c8b80-17a8-11eb-98bb-23800d625380.png)

2020-10-26 16:52 UTC, adamretter commented on exist-core/src/main/java/org/exist/source/AbstractSource.java
> +import net.jpountz.xxhash.XXHash64;
This PR is atop #3579

2020-10-26 16:53 UTC, adamretter commented
@dizzzz Ooof! Looks like I forgot to backport one of the fixes from FusionDB... I have now added it to this PR :-)

2020-10-26 18:08 UTC, dizzzz commented
in some builds...

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/1700062/97210903-8bb43400-17be-11eb-8870-af254d90d66f.png">

2020-10-27 08:01 UTC, dizzzz requested changes
not all builds are ok :-(

2020-10-27 14:05 UTC, dizzzz commented
For Java11 and 14 the same issue with "Module":

![image](https://user-images.githubusercontent.com/1700062/97312532-dd63c980-1865-11eb-81e3-4db916a58b1e.png)

2020-10-27 19:10 UTC, dizzzz commented
@adamretter I cannot apply this 
[patch.diff.txt](https://github.com/eXist-db/exist/files/5447548/patch.diff.txt)

2020-10-28 12:50 UTC, adamretter commented
@dizzzz Should be fixed now. JDK 9+ has its own `Module` class...

2020-10-28 12:54 UTC, dizzzz commented
yes I figured out about java9...

2020-10-28 12:54 UTC, dizzzz approved these changes

2020-10-28 12:58 UTC, dizzzz commented
Where is the change? looks not in this PR?

2020-10-28 12:59 UTC, adamretter commented
@dizzzz It is the commit titled "[bugfix] Fix compilation on JDK 9+"

2020-10-28 13:17 UTC, dizzzz commented
right :-) I was looking for the import change, but this is indeed better

2020-10-28 15:48 UTC, dizzzz commented
Wohooooo

2020-10-28 15:48 UTC, merged