[feature] Add a  parameter to util:eval to preserve the original erro…
eXist-db/exist pull request #3588
Opened 2020-10-28 17:39 UTC by adamretter

This back-ports a feature to eXist-db from FusionDB. The feature adds a `$pass` parameter to `util:eval`. This is similar to the BaseX option, it preserves the line and column number of any error within the evaluated string, rather than setting it to that of the `util:eval` expression.

Closes https://github.com/eXist-db/exist/issues/3513

2020-10-28 19:07 UTC, dizzzz approved these changes

2020-10-28 19:09 UTC, dizzzz requested changes
License check fails :-/

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/1700062/97484768-7cb5b900-1959-11eb-9434-1307cf3978ab.png">

2020-11-02 23:53 UTC, adamretter commented
@dizzzz Should be all sorted now.

2020-11-03 10:05 UTC, dizzzz approved these changes

2020-11-03 10:05 UTC, merged