Make CI more manageable
eXist-db/exist pull request #3766
Opened 2021-03-06 08:55 UTC by duncdrum

Speed up ci by increasing parallelism, giving us more control over restarting Workflows

add unit test for docker images and run them on ci

2021-03-06 14:27 UTC, line-o reviewed
That looks promising. A lot of good stuff. Can't wait to see the final version.

2021-03-06 14:27 UTC, line-o commented on exist-docker/src/test/bats/02-config-spec.bats
> +@test "log queries to sytem are visible to docker" {
Typo "system"

2021-03-08 00:01 UTC, duncdrum commented
I've tested publishing from this script to my own repo and it works, so the message about lacking credentials means the wrong credentials are in this repo. I cannot edit things on docker hub. So adding mine here won't do the trick. 

To make sure we have the right credentials, simply restart the `deploy` workflow after editing them. 

Once this is merged we should swiftly comment out [L55-66](]https://github.com/eXist-db/exist/actions/runs/630622367/workflow#L59-L66) there is no harm in pushing `experimental` tags it simply adds noise after the first one or two.

2021-03-08 18:36 UTC, dizzzz commented
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/1700062/110365652-907ad580-8045-11eb-9700-3cf95a14bdd3.png">

2021-03-08 19:53 UTC, duncdrum commented
It just occurred to me that secrets being unavailable from PRs might be a feature of gha secrets. Since we're not deploying from develop right now, I vote to merge this and see if that fixes our problem.

2021-03-09 09:52 UTC, adamretter commented
@duncdrum I don't think that can be the case, as for the SonarCloud one we had a secret key we had to set `SONAR_TOKEN` and as far as I can see, that worked fine in a PR.

2021-03-09 09:55 UTC, duncdrum commented
@adamretter the sonar token is an org secret, the docker stuff is a repo secret. GH-A handles secrets differently compared to Travis, Circle etc so i m still trying to figure it out. But I strongly suspect that to be the case. I would like to see a run on develop first to confirm, so we can adjust accordingly later

2021-03-09 09:58 UTC, adamretter commented
Okay can you prepare a pr which is s single commit and just the deploy step, I can merge that to develop for testing. This pr mixes in other stuff and I'd like to keep it lean for testing on develop

2021-03-16 21:38 UTC, dizzzz commented
<img width="520" alt="image" src="https://user-images.githubusercontent.com/1700062/111383269-47133180-86a8-11eb-94b9-9119c2108f07.png">

2021-03-16 21:38 UTC, dizzzz requested changes
need rework

2021-03-17 09:14 UTC, duncdrum commented
rebase and its running, once this is merged we should consider removing appveyor either all together, or at least limits its matrix, as it is slowing us down and just duplicating environments.

2021-03-17 12:59 UTC, adamretter commented
@duncdrum I reworded your commit messages to match the documented standard for eXist-db. Assuming that CI passes again, I will get this merged...

2021-03-17 15:12 UTC, merged