Tests for computed namespace constructor
eXist-db/exist pull request #3781
Opened 2021-03-20 23:07 UTC by adamretter

2021-03-21 12:14 UTC, duncdrum commented
[L96](https://github.com/eXist-db/exist/pull/3781/checks?check_run_id=2159559099#step:5:96):

```
Error:  Failed to execute goal com.mycila:license-maven-plugin:4.0.rc1:check (check-headers) on project exist-core: Some files do not have the expected license header -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :exist-core
Error: Process completed with exit code 1.
```

2021-03-21 12:15 UTC, duncdrum requested changes
does `exist-core/src/test/xquery/xquery3/computed-namespace-constructor.xql` need a license?

2021-03-21 13:24 UTC, adamretter commented
@duncdrum Oops! I added that now.

2021-03-22 08:45 UTC, duncdrum approved these changes
CI has network issues, but all in all this looks good

2021-03-22 13:54 UTC, dizzzz approved these changes

2021-03-25 09:51 UTC, dizzzz commented
OK to pull?

2021-03-25 10:03 UTC, line-o commented on exist-core/src/main/java/org/exist/xquery/NamespaceConstructor.java
> +        if (prefix.equals(XMLConstants.XMLNS_ATTRIBUTE)) {
For me this is refactoring code, not reformatting it.

2021-03-25 10:04 UTC, line-o commented on exist-core/src/main/java/org/exist/xquery/NamespaceConstructor.java
> +    public NamespaceConstructor(final XQueryContext context) {
If this is just reformatting code is debatable.

2021-03-25 10:05 UTC, line-o commented
@dizzzz I do not know about appveyor. It seems to always fail on ubuntu, but you could try to restart it once again. I am still in favour of dropping appveyor completely.

The code analysis fails because of the code formatting _and_ the minor refactoring that happened in NamespaceConstructor.java - that triggers new analysis and the eval method had and still has a _high_ complexity.

2021-03-25 10:07 UTC, line-o commented
So, I would like to see the commit message change to `[ignore] refactor and reformat NamespaceConstructor` other than that it looks good to me.

2021-03-25 15:14 UTC, adamretter commented
@line-o I changed the commit message as requested

2021-03-25 20:28 UTC, merged