Simplify storage of predicates for a step
eXist-db/exist pull request #3975
Opened 2021-07-12 21:34 UTC by adamretter

* Removes unnecessary use of `CopyOnWriteArrayList` in code that is non-concurrent
* Optimised for the case where there are no or very few predicates on each step - which is typical in XQuery!
    * Uses zero memory to store predicates when there are no predicates on a path step
    * Reduces unnecessary processing per step

2021-07-13 12:26 UTC, dizzzz commented on exist-core/src/main/java/org/exist/xquery/Step.java
> +        final Predicate[] newPredicates = new Predicate[predicates.length + 1];
NPE risk !? predicates can still be null

2021-07-13 12:28 UTC, dizzzz approved these changes

2021-07-13 12:28 UTC, dizzzz commented on exist-core/src/main/java/org/exist/xquery/Step.java
> +        final Predicate[] newPredicates = new Predicate[predicates.length + 1];
ah no, (previousIdx < 0) will shield

2021-07-16 08:24 UTC, dizzzz approved these changes

2021-07-27 13:50 UTC, dizzzz approved these changes

2021-07-27 13:51 UTC, dizzzz commented
One bug detected? https://sonarcloud.io/project/issues?id=eXist-db_exist&pullRequest=3975&resolved=false&types=BUG

2021-07-27 15:24 UTC, dizzzz requested changes
build issue

2021-07-27 15:55 UTC, adamretter commented
> One bug detected? https://sonarcloud.io/project/issues?id=eXist-db_exist&pullRequest=3975&resolved=false&types=BUG

@dizzzz I think it's a false positive by Sonarcloud, as it is handled by `if (previousIdx < 0) {`

2021-08-02 21:51 UTC, adamretter commented
@dizzzz I removed an additional commit to this PR that I sent by mistake

2021-08-03 08:31 UTC, dizzzz approved these changes

2021-08-03 08:32 UTC, merged