Cleanup of XML Reader Pool
eXist-db/exist pull request #4021
Opened 2021-08-30 21:46 UTC by adamretter

Many small improvements... API has been kept the same.
Fixed a bunch of issues where XMLReaders were reused but not correctly reset.

2021-08-31 20:52 UTC, dizzzz commented
Nice changes, sorry for the typo ( :-)), good tests.

2021-08-31 20:52 UTC, dizzzz approved these changes

2021-08-31 20:54 UTC, dizzzz requested changes
test issue... not always? 
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/1700062/131574455-1de1ed45-a842-4f4d-80c0-2f82dadbcdae.png">

2021-08-31 22:16 UTC, adamretter commented
@dizzzz it's a proper issue... I'm digging into it, but it's elusive...

2021-09-08 08:25 UTC, dizzzz approved these changes

2021-09-08 09:02 UTC, merged