[4.x.x] Do not override Bearer Authentication with Basic Authentication
eXist-db/exist pull request #4377
Opened 2022-05-02 12:31 UTC by adamretter

Backport of https://github.com/eXist-db/exist/pull/4375

2022-05-02 17:46 UTC, dizzzz requested changes
According to [RFC 7617](https://datatracker.ietf.org/doc/html/rfc7617) "both scheme and parameter names are matched case-insensitively."

2022-05-02 20:24 UTC, adamretter commented
@dizzzz Thanks :-) Indeed... you are correct, I have updated all 3-PR's to fix that now.

2022-05-03 14:31 UTC, dizzzz commented on exist-core/src/main/java/org/exist/http/servlets/BasicAuthenticator.java
> +				dec.translate(credentials.substring("basic ".length()));
can still contain Basic ?

2022-05-03 14:32 UTC, dizzzz approved these changes

2022-05-03 14:32 UTC, merged