Implement fn:nillled
eXist-db/exist pull request #4405
Opened 2022-05-24 07:33 UTC by alanpaxton

### Description:

Implementation of the xquery `fn:nilled#0` function: (and changes to unlinked `fn:nilled#1` to support)

### Reference:

See https://www.w3.org/TR/xpath-functions-31/#func-nilled.

### Type of tests:

Unit tests have been added in fn-nilled.xqm.

In addition, XQTS suite tests were run with `sbt "run --xqts-version HEAD --test-set fn-nilled"`

There is 1 remaining failure should be the XQTS tests for `fn:nilled`:

| test | result | description |
| -- | -- | -- |
| fn-nilled-29 | Failure | Expected: 'Error(XPTY0004)', but query returned: 'fn:nilled#0' |

This occurs because eXist-db at present has no support for predicates on Function References (`NamedFunctionReference.java`) and as such completely ignores the Predicate. This is not directly related to these changes in this PR and should be fixed elsewhere.

--

This open source contribution to the eXist-db project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov.

2022-05-24 19:08 UTC, dizzzz requested changes
quite a lot of tests are failing.

2022-07-15 06:06 UTC, joewiz commented
@alanpaxton You wrote:

> This occurs because eXist-db at present has no support for predicates on Function References (NamedFunctionReference.java) and as such completely ignores the Predicate. This is not directly related to these changes in this PR and should be fixed elsewhere.

I tried to interpret what you meant by "predicates on function references" and crafted this query:

```xquery
(tokenize#1)("a b c")[2]
```

... which applies a predicate to a function reference and returns "b" with eXist develop. Did I misinterpret your description  of what eXist lacks support for?

2022-07-15 06:12 UTC, joewiz commented
@alanpaxton Ah, I see. Tracing the mention of fn-nilled-29 to https://github.com/w3c/qt3tests/blob/master/fn/nilled.xml#L329-L340, I see the equivalent that eXist should support is:

```xquery
current-date#0[false()]
```

Whereas BaseX and Saxon return the empty sequence, eXist returns the function reference.

2022-07-27 08:55 UTC, dizzzz approved these changes

2022-07-27 08:56 UTC, merged