[bugfix] Add missing location information in errors for functions inside element constructors (err:XQTY0105)
eXist-db/exist pull request #4444
Opened 2022-06-15 01:38 UTC by chris-evolvedbinary

### Description:

Add location information to map expressions, and pass this information to the `XQTY0105` exception that occurs when an enclosed expression contains a function item

### Reference:

https://github.com/eXist-db/exist/issues/3623

### Type of tests:

`subexpression-in-enclosed-expression-evaluates-to-map` and `enclosed-expression-evaluates-to-map` in `exist-core\src\test\xquery\errors.xql`

--

This open source contribution to the eXist-db project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.

2022-06-15 07:24 UTC, dizzzz commented on exist-core/src/main/java/org/exist/xquery/value/FunctionReference.java
> +    private Expression expression = null;
is this null assignment really needed?

2022-06-15 07:25 UTC, dizzzz approved these changes

2022-06-15 07:25 UTC, dizzzz commented
![image](https://user-images.githubusercontent.com/1700062/173768059-64c0f6bf-17b4-4b47-864d-836018ffe2bd.png)

2022-06-15 13:02 UTC, adamretter requested changes
This solves the problem for a Map expr inside an element constructor. But I think there are several more types of expr and function that we need to at least add tests for, and then fix potentially if they don't work already:

1. What about `ArrayExpr`?
2. What about evaluation of a`FunctionReference`? e.g. `let $f := function($x) { fn:error(xs:QName("local:my-error") } return element { $x() }`
3. What about `UserDefinedFunction`? i.e. functions implemented in XQuery? You could implement an XQuery function that wraps `fn:error` for testing this.
4. What about `BasicFunction`? i.e. functions for XQuery implemented in Java? You could use fn:error for testing this
5. What about other types of expression inside the element constructor... as just one example: Attribute Constructor:
`element e1 { attribute a1 { fn:error(xs:QName("local:my-error")) } }`

2022-06-15 22:47 UTC, chris-evolvedbinary commented
> This solves the problem for a Map expr inside an element constructor. But I think there are several more types of expr and function that we need to at least add tests for, and then fix potentially if they don't work already:
> 
> 1. What about `ArrayExpr`?
> 2. What about evaluation of a`FunctionReference`? e.g. `let $f := function($x) { fn:error(xs:QName("local:my-error") } return element { $x() }`
> 3. What about `UserDefinedFunction`? i.e. functions implemented in XQuery? You could implement an XQuery function that wraps `fn:error` for testing this.
> 4. What about `BasicFunction`? i.e. functions for XQuery implemented in Java? You could use fn:error for testing this
> 5. What about other types of expression inside the element constructor... as just one example: Attribute Constructor:
>    `element e1 { attribute a1 { fn:error(xs:QName("local:my-error")) } }`

The `exist-core/src/test/xquery/errors.xql` file already contains tests for these cases, except for the last case ("other types of expression inside the element constructor") for which I added a test.  All the tests pass.

The issue is that the `UserDefinedFunction`, `BasicFunction`, and `OpNumeric` class all derive from the `PathExpr` class, which has a list of expressions (as "steps").  So when errors occur for a `PathExpr` object, the location information is obtainable for an expression of the object.  The `MapType` class, however, derives from the `FunctionReference` class, which does not derive from the `PathExpr` class and therefore does not have information about the expression from which it came.  So the code for this pull request adds an expression property to the `FunctionReference` class.

Also, there does not appear to be an `ArrayExpr` class.  Instead, the `XQueryTreeParser` class uses the `ArrayConstructor` class, which like the `PathExpr` class has a list of expressions (as "arguments").

2022-06-30 17:35 UTC, adamretter commented
@chris-evolvedbinary I have pushed one commit which adds some additional tests to cover the issues I mentioned. Hopefully that is helpful?

4 of the tests I added do fail, so I think there are one or two more places where you need to expose the location information.

2022-07-26 14:48 UTC, adamretter approved these changes
LGTM

2022-07-26 14:48 UTC, merged