[bugfix] Fix ignored namespace binding conflict
eXist-db/exist pull request #4507
Opened 2022-07-27 21:42 UTC by chris-evolvedbinary

### Description:

Add error when namespace binding conflict occurs.

### Reference:

https://github.com/eXist-db/exist/issues/1482

### Type of tests:

Existing tests still work.

---

This open source contribution to the eXist-db project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.

2022-07-28 08:51 UTC, dizzzz commented
is there a way to implement a test for this? maybe @adamretter can help?

2022-07-28 08:53 UTC, dizzzz requested changes
Please add a (set of) test(s) as provided in the nice original problem report.

2022-07-28 12:02 UTC, line-o reviewed
Looks good but I do not see any tests for it. I would prefer them to be XQSuite tests.

2022-08-03 20:59 UTC, adamretter requested changes
I have just attempted the test in the linked issue. Unfortunately it shows that this is not the correct solution to the problem. We cannot statically detect this at compile time as this PR attempts to do, the issue we are trying to solve can only be detected at runtime.

2023-02-21 16:15 UTC, line-o commented
Can we close this PR, @adamretter? The linked issue is closed.

2023-04-07 20:00 UTC, duncdrum commented
As this is not the right fix, and there are pending change request I’ll convert this to draft

2026-09-21 18:28 UTC, closed without merging