fix resource leak (and file lock)
eXist-db/exist pull request #4521
Opened 2022-08-19 10:12 UTC by nverwer

This PR fixes a resource leak, which kept file handles around until they are garbage collected. This results in an incorrect file lock in Windows.

### Description:

This fixes a resource leak in `org.exist.xquery.value.BinaryValueFromFile`, which causes file handles to hang around.
Under Windows, this means that most editors cannot save such a file, once the handle has been created, because they consider the file locked. Under Linux, vi (and apparently, nano) have no problem. However, the resource leak still exists.

The problem occurs in line 64 of `BinaryValueFromFile.java`:

```
this.channel = new RandomAccessFile(file.toFile(), "r").getChannel();
```

The creation of the `RandomAccessFile` object creates the file handle. Because the `RandomAccessFile` object is not kept, its close() method can never be called.

2022-08-19 10:20 UTC, line-o approved these changes

2022-08-19 13:11 UTC, dizzzz approved these changes

2022-08-22 12:27 UTC, adamretter approved these changes
LGTM. We should also backport to `develop-5.x.x` and `develop-4.x.x` branches.
We may also want to search the code base for other uses of `RandomAccessFile` to make sure they are closed in the same manner.

2022-08-22 13:19 UTC, joewiz commented
Great! Are there any concerns about the CI failures?

2022-08-22 17:02 UTC, adamretter commented
I have now created the PRs to backport this for 4.x.x and 5.x.x.

2022-08-22 18:49 UTC, line-o commented
I was not able to reproduce the failing tests locally. We should investigate this further.
It seems to be only one failing test: xquery.CoreTests.non-existant

2022-08-22 19:25 UTC, line-o commented
With this patch applied on top of the current develop HEAD the tests all run on my local machine.

2022-08-23 10:13 UTC, line-o requested changes
I just checked out this PR and it fails at this test:
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.102 s <<< FAILURE! - in org.exist.repo.PackageTriggerTest
[ERROR] org.exist.repo.PackageTriggerTest  Time elapsed: 2.102 s  <<< ERROR!
java.io.IOException: storeDocument received a null InputStream when trying to store a Binary Document
	at org.exist.collections.MutableCollection.storeDocument(MutableCollection.java:1154)
        ...
```

2022-08-23 10:14 UTC, line-o commented
I will rebase this on top of current develop and see if the test failure vanishes.

2022-08-23 10:38 UTC, line-o commented
PackageTriggerTest passes when this PR is rebased on top of the current develop HEAD.
Now, I get the infamous numberX is not equal to numberX which I've seen in other test runs here.
The failure is highly likely unrelated to this PR.

```
INFO] Running org.exist.storage.structural.NativeStructuralIndexWorkerTest
[ERROR] Tests run: 14, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.574 s <<< FAILURE! - in org.exist.storage.CopyCollectionTest
[ERROR] org.exist.storage.CopyCollectionTest.copyToNonExistentAsSelf  Time elapsed: 0.006 s  <<< FAILURE!
java.lang.AssertionError:
Created value is not correct
Expected: not <1661250386077L>
     but: was <1661250386077L>
```

2022-08-23 11:59 UTC, line-o commented
A different recent test that fails with the numberX is not equal to numberX
https://github.com/eXist-db/exist/runs/7969942292?check_suite_focus=true#step:4:8899

2022-08-24 10:06 UTC, dizzzz commented
Pff looks like an assert/junit bug to me?

![image](https://user-images.githubusercontent.com/1700062/186391563-aa4c0075-d834-4af5-97e3-0523e8e92145.png)

2022-08-25 12:22 UTC, line-o approved these changes

2022-08-25 12:22 UTC, line-o commented
@nverwer would you be able to rebase your changes on top of develop?

2022-08-25 12:37 UTC, PieterLamers commented
Nico is away on holiday now, for two weeks, and he may not be able to act
right now, so if this is something someone else can do (I am completely
ignorant about rebasing) feel free.

Op do 25 aug. 2022 14:22 schreef Juri Leino ***@***.***>:

> @nverwer <https://github.com/nverwer> would you be able to rebase your
> changes on top of develop?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/eXist-db/exist/pull/4521#issuecomment-1227185787>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMOOYHERPHJ7OFPKZ5OBZFDV25QRRANCNFSM57AGLLRA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-08-25 13:46 UTC, dizzzz commented
is a rebase needed? what has changed in develop?  I wonders as this assert issue appears on more branches

2022-08-25 14:43 UTC, line-o commented
@dizzzz OK, I will merge this then?
@nverwer thanks for the contribution!

2022-08-25 14:43 UTC, merged