Remove the last small dependency on Apache Xalan
eXist-db/exist pull request #4643
Opened 2022-12-07 19:38 UTC by adamretter

We can use the equivalent classes from Apache Xerces instead

2022-12-07 22:23 UTC, dizzzz commented
In the unit tests we explicitly test for xalan 😬

2022-12-08 11:36 UTC, dizzzz commented
interesting... java8 only 
![image](https://user-images.githubusercontent.com/1700062/206437044-f9468747-5489-4862-bf17-39ea6355ba4c.png)

2022-12-08 16:07 UTC, adamretter commented
There is a runtime dependency on Xalan in the GeoTools libraries used by the Spatial Index. I have opened a PR to fix that here - [GEO-305](https://github.com/geotools/geotools/pull/4141). Once GEO-305 is merged, we will need to update the Spatial Index to use a newer version of the GeoTools.

2022-12-08 16:07 UTC, adamretter commented
> it looks the PR combines 2 PRs ?

@dizzzz now fixed.

2022-12-10 08:06 UTC, reinhapa approved these changes

2022-12-10 08:09 UTC, reinhapa commented
@adamretter seems there is no support for "namespace" feature: https://github.com/eXist-db/exist/actions/runs/3649983650/jobs/6165379878#step:4:13854

2022-12-10 09:33 UTC, adamretter commented
> @adamretter seems there is no support for "namespace" feature: https://github.com/eXist-db/exist/actions/runs/3649983650/jobs/6165379878#step:4:13854

@reinhapa Yup, that is addressed in my PR https://github.com/geotools/geotools/pull/4141

2022-12-14 08:09 UTC, dizzzz approved these changes

2023-02-05 17:54 UTC, adamretter commented
@dizzzz @reinhapa Okay so they released GeoTools 28.1 and I just updated this, so I am hopeful that assuming CI goes through okay, then it is now ready.

2023-02-05 20:13 UTC, dizzzz commented
craps 
<img width="784" alt="image" src="https://user-images.githubusercontent.com/1700062/216842511-f508509c-5eac-4f1f-b33c-a05a2abb4b70.png">

2023-02-05 23:16 UTC, adamretter commented
@dizzzz No problem. I have fixed that one now. However I have hit another one in GeoTools, I will need to send them a PR as they are not handling XML Namespaces in a manner that Saxon likes:

```java
Caused by: org.xml.sax.SAXException: Parser configuration problem: namespace reporting is not enabled
	at net.sf.saxon.event.ReceivingContentHandler.getNodeName(ReceivingContentHandler.java:477)
	at net.sf.saxon.event.ReceivingContentHandler.startElement(ReceivingContentHandler.java:366)
	at org.geotools.xml.transform.QNameValidatingHandler.startElement(QNameValidatingHandler.java:61)
	at org.geotools.xml.transform.TransformerBase$ContentHandlerFilter.startElement(TransformerBase.java:367)
	at org.geotools.xml.transform.TransformerBase$TranslatorSupport._start(TransformerBase.java:822)
```

2023-02-06 18:01 UTC, adamretter commented
Requires this second PR https://github.com/geotools/geotools/pull/4186 to be merged to GeoTools, and then a new release of GeoTools.
After that we will need to update this PR for the new release of GeoTools that includes the above GeoTools PR.

2023-04-07 20:22 UTC, duncdrum reviewed
@adamretter despite two approvals the upstream changes still need to get merged and released. And we need to get a ci run here before merging. I’ll convert this to draft in the interim. Changes look good in principal

2023-05-15 17:37 UTC, adamretter commented
The PR https://github.com/geotools/geotools/pull/4186 to GeoTools was merged a couple of weeks ago. We are now just waiting for a new release of GeoTools that includes that fix. Then we can bump the dependency version here and we will be good to go...

2024-09-02 15:52 UTC, dizzzz requested changes
I think this is a minor issue....

![image](https://github.com/user-attachments/assets/28314fdd-663f-4b14-98d2-b19a96d12f22)

2024-09-02 15:52 UTC, dizzzz commented on extensions/indexes/spatial/pom.xml
> +        <geotools.version>29.6</geotools.version>
Nice.... did not expect such a version bump works; I tried some works on it recently, and some reading....

2024-10-10 11:25 UTC, adamretter commented
@dizzzz @reinhapa I updated it to the latest version of GeoTools (which now finally includes all the changes I sent them) - tests appear to pass - WOOOHOO :-)

2024-10-11 08:22 UTC, dizzzz approved these changes

2024-10-11 08:22 UTC, merged

2024-10-11 08:22 UTC, dizzzz commented
nice work !

2024-10-11 08:25 UTC, adamretter commented
Thank you so much @dizzzz - it took almost 2 years, but we finally got there! We are now Xalan free 🥳

2024-10-12 16:47 UTC, dizzzz commented
Woooooohooo