context with a hint for xst info
eXist-db/exist pull request #4657
Opened 2022-12-18 21:07 UTC by line-o

add a hint that the context can be conveniently gathered using `xst info`
see https://github.com/eXist-db/xst/pull/49

2022-12-19 10:50 UTC, adamretter commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Context (please always complete the following information, you can past the output of `xst info` here):**
`past` -> `paste`.

Also could we improve the wording a little... perhaps?

```
information; one option is to use the [xst](URL GOES HERE) tool, and copy and paste the output produced by running `xst info` here.

2022-12-22 10:58 UTC, dizzzz requested changes
see comments

2022-12-22 14:05 UTC, line-o commented
@dizzzz yes... I gave it a thumbs up already no need to get loud.

2022-12-22 14:06 UTC, line-o commented
I will put this into draft until the actual feature in xst is available.

2023-01-17 15:21 UTC, dizzzz approved these changes

2023-01-20 14:30 UTC, line-o commented
see `xst info` output in for a preview #4694

2023-01-23 13:53 UTC, reinhapa approved these changes

2023-01-31 12:55 UTC, line-o commented
This PR is now open for 2 weeks and has two approvals.

2023-01-31 13:34 UTC, reinhapa commented
@line-o seems that you need to update the current `develop` as here your #4696 seems to missing...

2023-01-31 13:36 UTC, line-o commented
For this change as it only affects the GitHub issue template it makes no difference. This will solve itself by merging it into develop.

2023-01-31 13:39 UTC, line-o commented
I do not have that branch checked out. I edited the issue template directly on github.

2023-01-31 13:41 UTC, merged