Fix some issues with CLI args
eXist-db/exist pull request #4772
Opened 2023-02-28 19:12 UTC by adamretter

1. Previously `jmxclient.sh|.bat` would exit with an error.
2. Some `.sh|.bat` scripts did not have a CLI `--help` option, this has now been added to all.
3. Previously the usage text when passing `--help` at the CLI would show the application name as `AppAssemblerBooter` this has now been corrected.

2023-03-01 06:25 UTC, reinhapa commented
![image](https://user-images.githubusercontent.com/4694567/222061230-3062dbda-90d7-4cd7-84b3-7bb69314db3f.png)

@adamretter  Seem to be some dependencies being missing...

2023-03-03 10:33 UTC, adamretter commented
@reinhapa @dizzzz Oopps! It looks like I forgot to add a new file to my commit. Should be fixed now.

2023-03-03 17:08 UTC, reinhapa commented
@adamretter Could the remaining [Deploy / Build and Test Images](https://github.com/eXist-db/exist/actions/runs/4322554137/jobs/7551746764#step:11:66) error be related to this change?

2023-03-11 00:21 UTC, adamretter commented
> Could the remaining Deploy / Build and Test Images error be related to this change?

@reinhapa Yes they were. I have pushed a commit that fixes those now.

2023-03-11 16:32 UTC, reinhapa requested changes
@adamretter could you address those minor, easy to fix code smells too? After that it's ok for me...
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&sinceLeakPeriod=true&pullRequest=4772&id=eXist-db_exist

2023-03-11 18:02 UTC, adamretter commented
@reinhapa Thanks. I just pushed a commit to address the ones of those that made sense.

2023-03-11 18:52 UTC, reinhapa approved these changes

2023-03-13 18:38 UTC, dizzzz approved these changes

2023-03-13 18:48 UTC, merged