[6.x.x] tails of subsequences off by one
eXist-db/exist pull request #4851
Opened 2023-04-04 10:46 UTC by line-o

### Description:

Backport of #4850 

### Reference:

#4830 

### Type of tests:

XQSuite tests

2023-04-06 05:35 UTC, duncdrum reviewed
CI is stuck at dependency checks

2023-04-07 10:44 UTC, adamretter requested changes
Same small issues as discussed here - https://github.com/eXist-db/exist/pull/4850#pullrequestreview-1376080745

2023-04-19 12:21 UTC, adamretter approved these changes
Thanks for the improvements. Now LGTM :-)

2023-04-19 12:22 UTC, adamretter commented
@line-o Just needs 1 more approval from a core dev and then we can merge - @reinhapa as you reviewed and approved the non-backport would you be able to approve this one

2023-04-19 14:05 UTC, line-o commented
I want to point out that @duncdrum _is_ a member of the core team which makes him a core-dev to me.

2023-04-19 17:58 UTC, merged