prevent omitting results from collections with different index styles
eXist-db/exist pull request #4869
Opened 2023-04-17 09:02 UTC by marmoure

Fixes #3620 

when trying to Search in a collection with bunch of sub-collections with different index styles 
the optimizer was optimizing the query without checking if all sub-collections are fit to be optimized 

#3620 has a nice test suit to illustrate this issue thanks to @joewiz. we are passing those tests now

This open source contribution to the [exist](https://github.com/eXist-db/exist) project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.

2023-04-17 13:45 UTC, dizzzz commented on extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/Lookup.java
> +//        return Optimizable.super.canOptimizeSequence(contextSequence);
please remove line

2023-04-17 15:35 UTC, marmoure commented on extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/Lookup.java
> +//        return Optimizable.super.canOptimizeSequence(contextSequence);
done

2023-04-18 12:41 UTC, adamretter requested changes
Just some small comments and suggestions.

2023-04-18 12:41 UTC, adamretter commented on exist-core/src/main/java/org/exist/xquery/pragmas/Optimize.java
> +                        //TODO compare canOptimizeSequence output to contextSequence
Remove the `TODO` from the start of this comment line, as it is now done.

2023-04-19 10:06 UTC, adamretter commented on extensions/indexes/range/src/test/xquery/range/optimizer.xql
> -    %test:assertError("range:EXXQDYFT0001")
Wouldn't that constitute a regression?
Would my suggestion to set the useCollation flag here - https://github.com/eXist-db/exist/pull/4869#discussion_r1169973507 solve that?

2023-04-19 11:16 UTC, marmoure commented on extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/Lookup.java
> +        canOptimize = optimizables.getItemCount() == contextSequence.getItemCount();
`canOptimizeSequence`  does not provide a fallback 
```java
if (fallback instanceof Optimizable) {
    return ((Optimizable)fallback).canOptimize(contextSequence);
}
```

2023-04-19 11:28 UTC, marmoure commented on extensions/indexes/range/src/test/xquery/range/optimizer.xql
> -    %test:assertError("range:EXXQDYFT0001")
After i added this commit https://github.com/eXist-db/exist/pull/4869/commits/f7e42467295c4c16c2b5268d95024e25d87635cc
The test is returing the orginal results

2023-04-20 06:39 UTC, dizzzz commented
nice work!

2023-05-15 20:58 UTC, marmoure commented on extensions/indexes/range/src/test/xquery/range/multi-collection-search.xqm
> +(: this is still failing due to a bug in matches:)
after #4885  was merged this will be uncommented

2023-05-16 06:13 UTC, reinhapa approved these changes

2023-05-16 08:42 UTC, marmoure commented
The build is failing for now, once #4924 is merged the build will return to normal

2023-05-30 06:28 UTC, dizzzz commented
@marmoure  please could you rebase?

2023-07-10 18:01 UTC, adamretter commented on exist-core/src/main/java/org/exist/xquery/pragmas/Optimize.java
> +                        //TODO compare canOptimizeSequence output to contextSequence
Done.

2023-07-10 18:02 UTC, adamretter commented on extensions/indexes/range/src/test/xquery/range/multi-collection-search.xqm
> +(: this is still failing due to a bug in matches:)
Done.

2023-07-10 18:03 UTC, adamretter commented on extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/Lookup.java
> +        canOptimize = optimizables.getItemCount() == contextSequence.getItemCount();
It has now been fixed.

2023-07-10 18:03 UTC, adamretter commented on extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/Lookup.java
>      public boolean canOptimize(Sequence contextSequence) {
This has now been done.

2023-07-10 18:06 UTC, adamretter approved these changes
All LGTM now. Thanks.

2023-07-17 18:01 UTC, merged