[hotfix] set enforce-index-use default value to strict
eXist-db/exist pull request #4885
Opened 2023-04-26 13:30 UTC by marmoure

Fixes #4884 
As discussed in #4884 we want to make the default value to be `strict`.

---
This open source contribution to the [exist](https://github.com/eXist-db/exist) project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.

2023-04-26 14:53 UTC, joewiz commented
Naturally, this PR would require a new major release. Today, this would mean it could be a candidate for eXist 7. So I'll set it for that milestone.

2023-04-27 17:45 UTC, adamretter commented
Tests will follow shortly...

2023-05-03 12:42 UTC, reinhapa requested changes

2023-05-03 12:42 UTC, reinhapa commented on extensions/indexes/indexes-integration-tests/src/test/java/org/exist/indexing/EnforceIndexUseTest.java
> +            throw new RuntimeException(e);
Remove this catch and add an additional throws declaration instead

2023-05-03 12:42 UTC, reinhapa commented on extensions/indexes/indexes-integration-tests/src/test/java/org/exist/indexing/EnforceIndexUseTest.java
> +import org.exist.xquery.value.Item;
Remove this unused import

2023-05-05 16:04 UTC, reinhapa requested changes

2023-05-05 16:04 UTC, reinhapa commented on extensions/indexes/indexes-integration-tests/src/test/java/org/exist/indexing/EnforceIndexUseTest.java
> +import org.exist.storage.txn.TransactionException;
The `TransactionException` import seems to be unused and should be removed...

2023-05-11 10:35 UTC, reinhapa approved these changes

2023-05-11 15:13 UTC, joewiz commented
@marmoure Thank you for this PR and adding the tests!

2023-05-15 18:49 UTC, adamretter approved these changes
LGTM. Thanks @marmoure

2023-05-15 18:49 UTC, merged