add support in `cache:create()` for 'expireAfterWrite' in `$config`
eXist-db/exist pull request #4975
Opened 2023-07-10 11:52 UTC by nverwer

### Description:

This feature adds a configuration option 'expireAfterWrite' to the `$config` parameter of `cache:create()`.
This option is available in the Caffeine cache, but was not supported in eXist.

### Reference:

I have not made a GitHub issue requesting this feature.

### Type of tests:

A test has been added to `extensions\modules\cache\src\test\xquery\modules\cache\cache.xqm`.
It is similar to the test for `expireAfterAccess`.

2023-07-10 14:19 UTC, joewiz commented
@nverwer Thank you for this PR! I see it's opened against the develop-6.x.x branch. I'm curious, do you plan to port it to develop so it's available for eXist 7.x and beyond?

2023-07-10 16:02 UTC, nverwer commented
@joewiz I could also put this in develop, but I would first have to get compilation working in Java 17.

2023-07-10 17:52 UTC, joewiz commented
@nverwer If it's convenient, could you please rebase now that https://github.com/eXist-db/exist/pull/4974 has been merged?

2023-07-10 19:16 UTC, nverwer commented
@joewiz I have rebased onto #4974 and force pushed. No news on java17 / 7.x.x yet...

2023-07-11 09:23 UTC, adamretter requested changes
There is a small issue in the documentation of the new function parameter. Once that is resolved, this is good to go. Thanks @nverwer

2023-07-11 19:02 UTC, nverwer commented on extensions/modules/cache/src/main/java/org/exist/xquery/modules/cache/CacheFunctions.java
> +            param("config", Type.MAP, "A map with configuration for the cache. At present cache LRU and permission groups may be specified, for operations on the cache. `maximumSize` is optional and
Thanks @adamretter for spotting this. I have made changes accordingly.

2023-07-11 19:14 UTC, nverwer commented
I have made a new pull request #4977 for the develop branch (eXist 7.x.x).

2023-07-11 19:35 UTC, adamretter commented
> I have made a new pull request https://github.com/eXist-db/exist/pull/4977 for the develop branch (eXist 7.x.x).

@nverwer Thanks :-) As your other PR only has one commit, I squashed your two commits in this PR into one - so that they are equivalent.

2023-07-11 19:39 UTC, adamretter approved these changes
LGTM. Thanks @nverwer

2023-07-11 19:39 UTC, merged