New exist:time XQuery Pragma
eXist-db/exist pull request #5078
Opened 2023-10-04 22:57 UTC by adamretter

Forward port of https://github.com/eXist-db/exist/pull/5077

2023-10-05 07:09 UTC, dizzzz approved these changes

2023-10-05 07:10 UTC, dizzzz requested changes
Some dep issues..... not all builds are ok

2023-10-05 08:29 UTC, adamretter commented
> Some dep issues..... 

@dizzzz Hopefully that is fixed now...

2023-10-06 15:20 UTC, dizzzz approved these changes

2023-10-06 15:20 UTC, merged