[fix] handle IllegalStateException in file:list#2
eXist-db/exist pull request #5092
Opened 2023-10-16 18:30 UTC by line-o

fixes #5028

The Java code of DirectoryList can throw an IllegalStateException when a non-existent directory is supplied as its first argument. This exception class is now handled in file:list#2.

2023-10-16 18:31 UTC, dizzzz approved these changes

2023-10-16 18:33 UTC, reinhapa approved these changes

2023-10-16 18:42 UTC, line-o commented
We should consider adding a test for this.

```
file:directory-list('/non/existent', ())
```

2023-10-16 18:45 UTC, adamretter requested changes
As @line-o suggested, let's add a test...

2023-10-16 20:28 UTC, line-o commented
Test added

2023-10-16 21:07 UTC, line-o commented
6.x.x backport is #5093

2023-10-16 21:18 UTC, dizzzz approved these changes

2023-10-16 22:15 UTC, adamretter reviewed
1 comment otherwise this LGTM.

2023-10-16 22:15 UTC, adamretter commented on extensions/modules/file/src/main/java/org/exist/xquery/modules/file/FileErrorCode.java
> +    FileErrorCode(String code, String description) {
There parameters could be set `final`.

2023-10-17 12:09 UTC, reinhapa requested changes

2023-10-17 12:09 UTC, reinhapa commented on extensions/modules/file/src/main/java/org/exist/xquery/modules/file/DirectoryList.java
> +import org.exist.xquery.*;
Do we not prefer single line imports?

2023-10-17 12:47 UTC, line-o commented on extensions/modules/file/src/main/java/org/exist/xquery/modules/file/DirectoryList.java
> +import org.exist.xquery.*;
We do not enforce this consistently.

2023-10-17 12:58 UTC, reinhapa approved these changes

2023-10-19 07:49 UTC, line-o commented on extensions/modules/file/src/main/java/org/exist/xquery/modules/file/FileErrorCode.java
> +    FileErrorCode(String code, String description) {
done

2023-10-19 08:01 UTC, adamretter approved these changes
Thanks for addressing the code review, now LGTM.

2023-10-19 08:01 UTC, merged

2023-10-19 12:51 UTC, PieterLamers commented
Thanks everybody!