[refactor] Some automatic refactoring using IntelliJ
eXist-db/exist pull request #5147
Opened 2023-11-30 19:05 UTC by dizzzz

Some automatic refactoring using IntelliJ: use java 7/8/14/16 language features.

Grouped per commit.

2023-12-01 16:17 UTC, reinhapa commented
> @reinhapa yeah I spotted them, I will check if they were not already there.

Seems only one class being the issue, that you may can change with low effort...

2023-12-01 20:28 UTC, dizzzz commented
there are 3 classes, all previously risking the NPE :-(

the largest I could solve by simply not returning the null value, but the already defined QName.EMPTY_QNAME

```
@Override
    public final QName getQName() {
        return switch (getNodeType()) {
            case Node.ATTRIBUTE_NODE -> document.attrName[nodeNumber];
            case Node.ELEMENT_NODE, Node.PROCESSING_INSTRUCTION_NODE -> document.nodeName[nodeNumber];
            case NodeImpl.NAMESPACE_NODE -> document.namespaceCode[nodeNumber];
            case Node.DOCUMENT_NODE -> QName.EMPTY_QNAME;
            case Node.COMMENT_NODE -> QName.EMPTY_QNAME;
            case Node.TEXT_NODE -> QName.EMPTY_QNAME;
            case Node.CDATA_SECTION_NODE -> QName.EMPTY_QNAME;
            default -> null;
        };
    }
```

looks not to be of a problem right here, but it might be downstream.

for the other two... few... @adamretter @wolfgangmm  ?

2023-12-02 09:50 UTC, adamretter commented
> for the other two... pfew... @adamretter 

@dizzzz I see 5 listed. Which of those are the one or two you would like me to take a look at?

2023-12-02 10:56 UTC, dizzzz commented
so there are 3 identical situations in NodeImpl.java, where we could just return the 'null' Qname
for the other 2.... no idea.

2023-12-04 19:14 UTC, reinhapa requested changes
Some small parts that can be simplified even more...

2023-12-04 19:14 UTC, reinhapa commented on exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
> +            }
`case NodeImpl.NAMESPACE_NODE -> XMLConstants.XMLNS_ATTRIBUTE_NS_URI;`

2023-12-04 19:14 UTC, reinhapa commented on exist-core/src/main/java/org/exist/dom/memtree/NodeImpl.java
> +            }
`default -> null;`

2023-12-04 19:25 UTC, reinhapa approved these changes

2023-12-05 05:58 UTC, reinhapa approved these changes

2023-12-05 16:26 UTC, line-o approved these changes
I like the changes :tada:

2023-12-08 07:15 UTC, reinhapa reviewed
@dizzzz getting better every day 💪

2023-12-11 18:39 UTC, merged