Simplify configration
eXist-db/exist pull request #5252
Opened 2024-03-18 19:19 UTC by reinhapa

Try to reduce complexity and sonar warnings

2024-03-18 19:33 UTC, line-o reviewed
Please have a second look at my comments

2024-03-18 19:33 UTC, line-o commented on exist-core/src/main/java/org/exist/util/Configuration.java
> +                                   final Map<String, Map<String, List<?>>> moduleParameters
This might create problems as this is now non-reifiable type

2024-03-18 19:33 UTC, line-o commented on exist-core/src/main/java/org/exist/util/Configuration.java
> +    public record StartupTriggerConfig(String clazz, Map<String, List<?>> params) {
This might create problems as this is now non-reifiable type

2024-03-24 14:58 UTC, dizzzz approved these changes

2024-03-25 19:09 UTC, dizzzz requested changes
<img width="1336" alt="image" src="https://github.com/eXist-db/exist/assets/1700062/67e3b613-6d69-4bed-9c4f-88312206b13f">

2024-04-30 14:15 UTC, line-o reviewed
Looks completely fine to me! Thanks for this @reinhapa 
Only the commit messages need to follow our commit message format then this can go in.
Or do you want to do further changes before this should be merged?

2024-08-26 18:14 UTC, line-o commented
@reinhapa Is this ready to go?

2024-10-12 16:42 UTC, dizzzz approved these changes

2024-10-13 14:49 UTC, line-o approved these changes
Thank you @reinhapa for this!

2024-10-13 14:49 UTC, merged