[6.x.x] Fix errors on update operations
eXist-db/exist pull request #5296
Opened 2024-05-02 11:00 UTC by line-o

Backport of #5276
refs #5273

2024-05-02 11:10 UTC, adamretter commented
The outstanding issues need to be addressed first please - https://github.com/eXist-db/exist/pull/5276#issuecomment-2079676651

2024-05-02 11:36 UTC, line-o commented
The test is different from the one in the original PR targeted at develop.

2024-05-02 11:39 UTC, adamretter commented
> The test is different from the one in the original PR targeted at develop.

Okay, but develop needs to be fixed first... Then those same commits can either be in this PR, or in a separate PR to 6.x.x.

2024-05-02 18:28 UTC, line-o commented
Please see the actual test that is part of the PR.

2024-10-11 09:30 UTC, reinhapa approved these changes

2024-10-11 09:43 UTC, adamretter requested changes
This PR (#5296) is a backport to 6.x.x of #5276 (which targeted `develop`). My concern is that #5276 was rushed and merged into `develop` whilst reviews were still identifying issues. This has led to #5276 actually introducing problems into `develop` by leaking resources in its tests. I asked for this to be fixed in April 2024 in both PRs. This has not yet been done. As this PR (#5296) is a backport, it has the same leak issues as #5276 and so cannot yet be merged.

To resolve this, the author (as I have requested), or anyone, needs to:
1. send a new PR to `develop` to fix the resource leak problems introduced by #5276
2. get that new PR through review and then merged.
3. append the bugfix commit(s) from that new PR into this PR (#5296).
4. we can then re-review this PR (#5296) and hopefully get it merged.

2024-10-14 18:10 UTC, dizzzz approved these changes

2024-10-14 18:10 UTC, dizzzz commented on exist-core/src/test/java/org/exist/xquery/update/UpdateInsertTriggersDefrag.java
> +        testCollection.close();
good. no resource leak

2024-10-18 13:04 UTC, line-o commented
This PR has now the needed approvals of two members of the core-team.

2024-10-18 13:07 UTC, line-o commented
This can be considered a fix - the tests do differ between version 6 and 7 because of the breaking changes in XML-DB API
The aforementioned issue - resource leak in the test class - is addressed.

2024-10-20 11:37 UTC, adamretter commented
> 1. send a new PR to develop to fix the resource leak problems introduced by https://github.com/eXist-db/exist/pull/5276

I have sent a PR to address the issues introduced by #5276 here - https://github.com/eXist-db/exist/pull/5503

2024-10-24 13:12 UTC, adamretter approved these changes
This now with my additions looks correct.

2024-10-24 14:09 UTC, merged