Allow setting the namespace on the result of sql:execute
eXist-db/exist pull request #5504
Opened 2024-10-20 11:42 UTC by adamretter

Forward port of https://github.com/eXist-db/exist/pull/5186

2024-10-20 11:44 UTC, dizzzz approved these changes

2024-10-20 11:56 UTC, dizzzz requested changes
Build NOK; ArrayOutOfBound exception

2024-10-20 22:49 UTC, adamretter commented
> Build NOK; ArrayOutOfBound exception

@dizzzz looks like a blip... Now passing!

2024-10-21 07:52 UTC, dizzzz approved these changes

2024-10-21 08:39 UTC, dizzzz commented
@dependabot rebase

2024-10-21 08:46 UTC, reinhapa approved these changes

2024-10-21 17:11 UTC, merged