[6.x.x] allow module imports in one-off xqueries
eXist-db/exist pull request #5586
Opened 2024-12-20 11:13 UTC by line-o

backport of #5529

2024-12-20 11:45 UTC, reinhapa requested changes

2024-12-20 11:45 UTC, reinhapa commented on exist-core/src/test/java/org/exist/xquery/AbsolutePathTests.java
> +
This change should be reverted as it does provide any change...

2024-12-20 13:31 UTC, line-o commented
@reinhapa more importantly the test-failure needs to be addressed.

2024-12-20 14:44 UTC, line-o commented
Turns out that the order of the first two parameters of `XqueryContext.compileOrBorrowModule` is reversed on develop
(see 4b92888ce3a787b3abe03882559cbf29b88b967a)

2024-12-20 19:46 UTC, line-o commented
Windows tests are super flaky. Each run something fails but each time a different test. Is that known?

2024-12-22 09:05 UTC, dizzzz commented
Interesting, I see indeed sometimes just a test fail....

2025-01-06 19:30 UTC, dizzzz approved these changes

2025-01-09 06:20 UTC, reinhapa approved these changes

2025-01-09 09:33 UTC, merged